name: Continuous Integration

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main

# permissions: write-all

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Tests
      run: |
        echo "Hello World"
  
  build-and-push:
    name: Release
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
    - name: debug
      run: |
        env
        echo ${{ github.env }}

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: google-github-actions/release-please-action@v3
      if: ${{ github.ref_name == 'main' }}}
      with:
        release-type: go
    
    - name: Get Build timestamp and branch name
      run: |
        echo "BUILD_TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
        echo "VERSION=$( echo ${{ github.head_ref || github.ref_name }} | tr '/' '-' )" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        build-args: |
          VERSION=${{ env.VERSION }}
          BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
          COMMIT_HASH=${{ github.sha }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          ghcr.io/${{ github.repository }}:${{ github.sha }}

